GROUP=dev.alllexey
VERSION_NAME=2.0.0
POM_ARTIFACT_ID=my-itmo-api-kmp
POM_NAME=my-itmo-api-kmp
POM_DESCRIPTION=An interface for MyITMO service
POM_URL=https://github.com/alllexey-dev/my-itmo-api
POM_LICENSE_NAME=MIT License
POM_LICENSE_URL=https://www.opensource.org/licenses/mit-license.php
POM_DEVELOPER_NAME=Aleksey Makarov
POM_DEVELOPER_ORGANIZATION=dev.alllexey
POM_DEVELOPER_ORGANIZATION_URL=https://github.com/alllexey-dev
POM_SCM_CONNECTION=scm:git:git://github.com/alllexey-dev/my-itmo-api.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://github.com:alllexey-dev/my-itmo-api.git
POM_SCM_URL=https://github.com/alllexey-dev/my-itmo-api/
org.gradle.daemon.idletimeout=1800000
org.gradle.jvmargs=-Xmx2g -XX:+UseParallelGC
kotlin.daemon.jvmargs=-Xmx1g
kotlin.mpp.applyDefaultHierarchyTemplate=false
